### ISSUE TITLE
Use pyproject.toml to be able to handle extras

### ISSUE THREAD

**Issue by Trymzet** [dyvenia/viadot#604]
The image size is pretty big now and builds are slow, and it seems each `viadot` deployment needs different connectors.

We can control them using the "extras" feature. For example, in `poetry`:
```toml
[tool.poetry.dependencies]
databricks-connect = { version="^10.4.8", optional=true }

[tool.poetry.extras]
databricks = ["databricks-connect"]
```
then, we can install viadot with eg. `pip install viadot[databricks]` to only include connectors of interest. We can still install it with all connectors easily with `pip install viadot[all]`
